<a href="https://colab.research.google.com/github/Bhaveshtarole/Monday-Machine-learning-M2L-/blob/week-1/Imbalanced_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Imbalanced  Datasets**
A dataset with an enequal class distribution

---



---

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
credit_card_data.shape

(284807, 31)

In [ ]:
#distribusion of the  two classes
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

0

*   0 ---> legit transaction
*   1---> fraud

In [ ]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

undersampling

In [ ]:
legit_sample = legit.sample(n = 466)

In [ ]:
print(legit_sample.shape)

(466, 31)

In [ ]:
#concatenate the two Dataframes
new_dataset = pd.concat([legit_sample,fraud],axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
132783,80110.0,-1.824050,0.750460,1.120322,1.158644,-0.184192,-0.196253,-0.008336,0.202622,-0.182532,...,-0.156936,-0.392619,-0.116801,-0.058439,0.238796,0.529912,-0.782660,0.247052,13.71,0
96332,65722.0,-0.385465,0.302716,1.541813,-0.295533,-0.149984,-0.318325,0.904720,-0.314142,-1.906274,...,-0.656018,-1.407048,0.086743,0.020357,-0.092564,0.351887,-0.147321,-0.152832,68.80,0
232013,147012.0,-1.284399,-0.651368,2.020863,0.459938,-0.470799,0.312455,-1.642772,0.694411,-1.321624,...,0.085697,0.382508,-0.204790,0.649739,-0.000126,0.240513,0.102634,-0.115163,15.26,0
5109,4780.0,-1.516765,-0.522377,1.659110,0.857315,1.290682,-0.849828,-0.328314,0.064824,0.582413,...,-0.159966,-0.265564,0.701557,0.160950,-0.765625,0.047519,-0.036704,0.291481,0.89,0
202068,134158.0,2.041683,-0.132462,-1.184367,0.228501,0.041354,-0.713778,0.053263,-0.149310,0.352051,...,-0.262251,-0.671601,0.292099,-0.344724,-0.296634,0.199362,-0.077055,-0.074042,1.79,0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [ ]:
new_dataset['Class'].value_counts()

Class
1    492
0    466
Name: count, dtype: int64